# Generated by Django 3.2.6 on 2021-08-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
