# Generated by Django 3.2.6 on 2021-08-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0002_alter_details_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='background_image',
            field=models.ImageField(default=None, upload_to='background_image'),
        ),
    ]
