# Generated by Django 3.2.6 on 2021-08-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0003_details_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='background_image'),
        ),
    ]
