# Generated by Django 3.2.6 on 2021-08-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0005_alter_details_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='background_image',
        ),
    ]
