# Generated by Django 3.2.6 on 2021-08-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0006_remove_details_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='background',
            field=models.ImageField(blank=True, upload_to='background'),
        ),
    ]
