# Generated by Django 3.2.6 on 2021-08-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0008_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='Wrire the description of the programming language'),
        ),
    ]
