# Generated by Django 3.2.6 on 2021-08-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0009_portfolio_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPortFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('careersummary', models.TextField(default='Write down career summary')),
                ('biography', models.CharField(default='Wirite down biography', max_length=1000)),
                ('skills', models.TextField(default='write down skills')),
            ],
        ),
    ]
