# Generated by Django 3.2.6 on 2021-08-11 02:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0010_myportfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myportfolio',
            name='careersummary',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='myportfolio',
            name='skills',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
