# Generated by Django 3.2.6 on 2021-08-11 02:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0011_auto_20210811_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='bio',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='myportfolio',
            name='biography',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
