# Generated by Django 3.2.6 on 2021-08-13 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0020_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='biography',
            new_name='bio',
        ),
    ]
