# Generated by Django 3.2.6 on 2021-08-13 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0021_rename_biography_service_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='service',
            name='careersummary',
        ),
    ]
